### PR TITLE
Wordpress gadgets update

### PR DESCRIPTION
**Pull request by erwanlr**
Some updates related to the WordPress gadgets

### CODE REVIEW

**Comment by cfreal** [comment]
Two remarks:
- What's with the `\P` namespace ? `Wordpress\WooCommerce` was enough, no ?
- `wordpress_gadgets.php` should be put in like `Wordpress/generic/gadgets.php` I think, it's less redondant and clearer.

WDYT ?

**Comment by erwanlr** [comment]
`P` namespace is for Plugins, as there can be Theme gadgets as well.

I've moved the `wordpress_gadgets.php` to `generic/gadgets.php`, even though creating a folder for that seems overkill, especially as it's not loaded automatically (which I thought it would given your comment ;p)

**Comment by cfreal** [comment]
Alright. Auto including generic gadgets is a feature I could add. Pushing, thank you Erwan :)

**Comment by erwanlr** [comment]
Great, will send another PR next week about more WP gadgets ;D

**Pull request merged**
