### PR TITLE
Adds an INFO GadgetChain

### PR DESCRIPTION
**Pull request by erwanlr**

### CODE REVIEW

**Comment by cfreal** [comment]
I'm actually hesitant to add this as this functionality is already achievable using `./phpggc something/rce1 -- phpinfo -1`. I don't feel it brings anything more to the table. Thoughts ?

**Comment by erwanlr** [comment]
If two args can be passed to the chain, yea sure this is useless.

However, in some cases, we might only have control over just one (like ```call_user_func($this->attr_we_can_control);``` and currently there is no way for the tool to support that (unless I missed something)

**Comment by cfreal** [comment]
Well, I guess it can't hurt. Thank you for the PR, pushed.

**Comment by erwanlr** [comment]
Youhouuu!

**Pull request merged**
